#
# Docker compose file running Flask app in development (debug) mode
# https://docs.docker.com/compose/compose-file/
#
version: "3.7"
services:
  app:
    # Set container & image name
    container_name: commandjobs
    image: commandjobs:1.0

    build:
      context: ..
      dockerfile: docker/Dockerfile

    # Set environment variables
    environment:
      - MENU_APP=src/menu.py
      - PYTHONPATH=/commandjobs

    # Mount entire project into docker container under /repo
    volumes:
      - ../:/commandjobs
      - ./docker-entrypoint.sh:/commandjobs/docker-entrypoint.sh

    # Use host network mode (may require changes depending on Docker environment)
    network_mode: host

    tty: true  # Allocate a pseudo-TTY
    stdin_open: true  # Keep STDIN open

    working_dir: /commandjobs
    entrypoint: ["sh", "/commandjobs/docker/docker-entrypoint.sh"]