#
# Docker compose file running Flask app in development (debug) mode
# https://docs.docker.com/compose/compose-file/
#
version: "3.7"
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    
    # Set container name
    container_name: commandjobs

    # Set environment variables
    environment:
      - MENU_APP=src/menu.py

    # Mount entire project into docker container under /repo
    volumes:
      - ../:/commandjobs
      - ./docker/docker-entrypoint.sh:/commandjobs/docker-entrypoint.sh

    network_mode: host

    tty: true  # Allocate a pseudo-TTY
    stdin_open: true  # Keep STDIN open
